setwd('/Users/kramerPro/Google Drive/Machine Learning/HW 1/')
library(readr)

data <- read_csv('letter-recognition.csv',col_names = F)

data[,2:17] <- data[,2:17]/15  # normalizing data

train <- data[1:10000,]
test <- data[10001:20000,]

A_B_train <- subset(train, X1 == 'A' | X1 == 'B')
write.csv2(A_B_train,file = '/Users/kramerPro/Google Drive/Machine Learning/HW 1/ABtrain.csv')

A_train <- train[train$X1=='A',]
A_test <- test[test$X1=='A',]
B_train <- train[train$X1=='B',]
B_test <- test[test$X1=='B',]
C_train <- train[train$X1=='C',]
C_test <- test[test$X1=='C',]
D_train <- train[train$X1=='D',]
D_test <- test[test$X1=='D',]
E_train <- train[train$X1=='E',]
E_test <- test[test$X1=='E',]
F_train <- train[train$X1=='F',]
F_test <- test[test$X1=='F',]
G_train <- train[train$X1=='G',]
G_test <- test[test$X1=='G',]
H_train <- train[train$X1=='H',]
H_test <- test[test$X1=='H',]
I_train <- train[train$X1=='I',]
I_test <- test[test$X1=='I',]
J_train <- train[train$X1=='J',]
J_test <- test[test$X1=='J',]
K_train <- train[train$X1=='K',]
K_test <- test[test$X1=='K',]
L_train <- train[train$X1=='L',]
L_test <- test[test$X1=='L',]
M_train <- train[train$X1=='M',]
M_test <- test[test$X1=='M',]
N_train <- train[train$X1=='N',]
N_test <- test[test$X1=='N',]
O_train <- train[train$X1=='O',]
O_test <- test[test$X1=='O',]
P_train <- train[train$X1=='P',]
P_test <- test[test$X1=='P',]
Q_train <- train[train$X1=='Q',]
Q_test <- test[test$X1=='Q',]
R_train <- train[train$X1=='R',]
R_test <- test[test$X1=='R',]
S_train <- train[train$X1=='S',]
S_test <- test[test$X1=='S',]
T_train <- train[train$X1=='T',]
T_test <- test[test$X1=='T',]
U_train <- train[train$X1=='U',]
U_test <- test[test$X1=='U',]
V_train <- train[train$X1=='V',]
V_test <- test[test$X1=='V',]
W_train <- train[train$X1=='W',]
W_test <- test[test$X1=='W',]
X_train <- train[train$X1=='X',]
X_test <- test[test$X1=='X',]
Y_train <- train[train$X1=='Y',]
Y_test <- test[test$X1=='Y',]
Z_train <- train[train$X1=='Z',]
Z_test <- test[test$X1=='Z',]
